[build-system]
requires = ["setuptools>=65.5", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "libensemble"
requires-python = ">=3.8"
authors = [
    {name = "Jeffrey Larson", email = "libensemble@lists.mcs.anl.gov"},
    {name = "Stephen Hudson"},
    {name = "Stefan M. Wild"},
    {name = "David Bindel"},
    {name = "John-Luke Navarro"},
]
license = {text = "BSD 3-clause"}
description = "Library to coordinate the concurrent evaluation of dynamic ensembles of calculations"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["numpy==1.23.4", "psutil==5.9.4", "setuptools==65.5.1", "pydantic==1.10.2"]
dynamic = ["version", "readme"]

[project.scripts]
liberegister = "scripts:liberegister"
libesubmit = "scripts:libesubmit"

[project.urls]
Homepage = "https://github.com/Libensemble/libensemble"

[project.optional-dependencies]
extras = [
    "ax-platform",
    "balsam",
    "DFO-LS",
    "dragonfly-opt",
    "funcx",
    "mpi4py",
    "mpmath",
    "nlopt",
    "petsc",
    "petsc4py",
    "psij-python",
    "pyyaml",
    "scipy"
]
docs = [
    "autodoc_pydantic",
    "sphinx",
    "sphinx_rtd_theme",
    "sphinxcontrib.bibtex"
]

testing = [
    "pytest-cov==2.12.1",
    "pytest-pep8>=1.0",
    "pytest-timeout==1.4.2",
    "mock==4.0.3",
    "flake8==5.0.4",
    "flake8-pep518==0.2.0",
    "coverage==5.5",
    "pytest==6.2.5",
    "coveralls==3.2.0",
    "python-dateutil==2.8.2"
]

[tool.setuptools.packages.find]
include = [
    "libensemble/*",
    "scripts/*",
    "examples/*",
    "setup.py",
    "*.cfg",
    "*.rst",
    "LICENSE",
    "CONTRIBUTING",
    "install/*"
]

exclude = [
    "*/__pycache__",
    "*/*.py[co]",
    "*/cov_*",
    "*/*.o",
    "*/*.npy",
    "*/*.gitignore"
]

[tool.setuptools.package-data]
"libensemble.sim_funcs.branin" = ["known_minima_and_func_values"]

[tool.setuptools.dynamic]
version = {attr = "libensemble.version.__version__"}
readme = {file = ["README.rst"]}

[tool.black]
line-length = 120
target-version = ["py37", "py38", "py39", "py310"]
force-exclude = """
(
  /(
    | \\.git
    | \\.github
  )/
    | libensemble/gen_funcs/old_aposmm.py
    | libensemble/gen_funcs/persistent_aposmm.py
    | libensemble/gen_funcs/aposmm_localopt_support.py
)
"""

[tool.codespell]
skip = ["_typos.toml","*.so","*.npy","*.mod","*.pyc","*.pickle",".git",
        "*.png","*.xml","*.bib","lapack.f","test_allocation_funcs_and_support.py"]
quiet-level = 1
ignore-words=".spell"

[tool.flake8]
max-line-length = 120

ignore = [
        # E203 is not PEP 8 compliant. https://github.com/PyCQA/pycodestyle/issues/373
        "E203",
        # Not worrying about spaces around arithmetic operations
        "E226",
        # Linebreaks before/after unary operators are okay
        "W503", "W504"
]
exclude = [
        # Don"t need to check .git
        ".git",
        # Largely autogenerated
        "docs/conf.py",
        # Keeping bad python format to match PETSc source code
        "libensemble/sim_funcs/chwirut1.py",
        "examples/sim_funcs/chwirut1.py"
]
# Note that you can use wildcard exceptions with something such as
# libensemble/libensemble/tests/regression_tests/*:F401
per-file-ignores = [
        # init needs to import the logger.
        "libensemble/__init__.py:F401",

        # Need to turn of matching probes (before other imports) on some
        # systems/versions of MPI:
        "libensemble/tests/standalone_tests/mpi_launch_test/create_mpi_jobs.py:E402",

        # Similar reasoning for configuring mpi4py
        "libensemble/tests/unit_tests/test_executor.py:E402",

        # Matplotlib needs something set before import
        "scripts/*:E402",

        # Ignoring linelength in APOSMM
        "libensemble/gen_funcs/*aposmm.py:E501",
        "examples/gen_funcs/*aposmm.py:E501",

        # Need to set something before the APOSMM import
        "libensemble/tests/scaling_tests/warpx/run_libensemble_on_warpx.py:E402",
        "examples/calling_scripts/run_libensemble_on_warpx.py:E402",
        "libensemble/gen_funcs/persistent_aposmm.py:E402, E501",
        "libensemble/tests/regression_tests/test_persistent_aposmm*:E402",
        "libensemble/tests/regression_tests/test_persistent_gp_multitask_ax.py:E402",
        "libensemble/tests/functionality_tests/test_uniform_sampling_then_persistent_localopt_runs.py:E402",
        "libensemble/tests/functionality_tests/test_active_persistent_worker_abort.py:E402",
        "libensemble/tests/deprecated_tests/test_old_aposmm*:E402",
        "libensemble/tests/unit_tests/test_persistent_aposmm.py:E402",

        # Allow undefined name "__version__"
        "setup.py:F821"
]