name: init-libEnsemble-CI
on: [push]
jobs:
    test-check-libE-py-version:

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest]
                python-version: [3.6, 3.7, 3.8]

        steps:
        - uses: actions/checkout@v2
        - name: Set up Conda with Python ${{ matrix.python-version }}
          uses: s-weigand/setup-conda@v1
          with:
            update-conda: true
            python-version: ${{ matrix.python-version }}
            conda-channels: anaconda, conda-forge
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8
            pip install -e .
        - name: Get versions, flake8
          run: |
            conda --version
            which python
            python --version
            python -c "import libensemble; print(libensemble.__version__)"
            flake8
