name: init-libEnsemble-CI
on: push
jobs:
    test-libE:

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-16.04, macos-latest]
                python-version: [3.6, 3.7, 3.8]
                comms-type: [m, l]
                exclude:
                    - os: macos-latest
                      python-version: 3.6

        env:
            HYDRA_LAUNCHER: 'fork'

        steps:
        - uses: actions/checkout@v2
        - name: Setup conda - Python ${{ matrix.python-version }}
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: condaenv
            miniconda-version: "latest"
            python-version: ${{ matrix.python-version }}
            channels: conda-forge
            channel-priority: flexible

        - name: SSH to GitHub Actions
          uses: P3TERX/ssh2actions@v1.0.0

        - name: Install Octave on Ubuntu
          if: matrix.os == 'ubuntu-16.04'
          run: |
            sudo apt-get install octave

        - name: Conda install dependencies, with-batch PETSc
          if: matrix.python-version == 3.8
          env:
            PETSC_CONFIGURE_OPTIONS: '--with-batch'
          run: |
            conda install nlopt
            conda install scipy
            conda install mpich
            conda install mpi4py
            conda install petsc4py

        - name: Conda install dependencies
          if: matrix.python-version != 3.8
          run: |
            conda install nlopt
            conda install scipy
            conda install mpich
            conda install mpi4py
            conda install mumps-mpi
            conda install petsc
            conda install petsc4py

        - name: Install pip dependencies
          run: |
            conda install libblas libopenblas psutil
            python -m pip install --upgrade pip
            pip install DFO-LS
            pip install deap
            pip install flake8
            pip install coverage==4.5.4
            pip install pytest
            pip install pytest-cov
            pip install pytest-timeout
            pip install mock
            pip install coveralls

        - name: Install Tasmanian on Ubuntu
          if: matrix.os == 'ubuntu-16.04'
          run: |
            pip install scikit-build packaging Tasmanian --user

        - name: Install libEnsemble, final before-test checks and adjusts
          run: |
            python install/find_mpi.py
            mpiexec --version
            pip install -e .
            flake8 libensemble
            ulimit -Sn 10000

        - name: Run tests
          run: |
            ./libensemble/tests/run-tests.sh -A "-W error" -z -${{ matrix.comms-type }}
            mv libensemble/tests/.cov* .
            coveralls
